# Generated by Django 3.0.3 on 2020-04-29 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('agency_id', models.AutoField(primary_key=True, serialize=False)),
                ('agency_name', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['agency_country', 'agency_name'],
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['company_country', 'company_name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('country_id', models.AutoField(primary_key=True, serialize=False)),
                ('country_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Type',
            fields=[
                ('type_id', models.AutoField(primary_key=True, serialize=False)),
                ('type_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Year',
            fields=[
                ('year_id', models.AutoField(primary_key=True, serialize=False)),
                ('year_name', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Sneakers',
            fields=[
                ('sneakers_id', models.AutoField(primary_key=True, serialize=False)),
                ('sneakers_name', models.CharField(max_length=50)),
                ('sneakers_url', models.CharField(max_length=500)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sneakers', to='sneakersinfo.Company')),
                ('publish_year', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sneakers', to='sneakersinfo.Year')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sneakers', to='sneakersinfo.Type')),
            ],
            options={
                'ordering': ['company', 'publish_year'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_quantity', models.IntegerField()),
                ('date', models.DateField()),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='sneakersinfo.Agency')),
                ('sneakers', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to='sneakersinfo.Sneakers')),
            ],
            options={
                'ordering': ['date', 'agency'],
            },
        ),
        migrations.AddField(
            model_name='company',
            name='company_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='companies', to='sneakersinfo.Country'),
        ),
        migrations.AddField(
            model_name='agency',
            name='agency_country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='agencies', to='sneakersinfo.Country'),
        ),
        migrations.AlterUniqueTogether(
            name='company',
            unique_together={('company_country', 'company_name')},
        ),
        migrations.AlterUniqueTogether(
            name='agency',
            unique_together={('agency_country', 'agency_name')},
        ),
    ]
