# Generated by Django 3.0.3 on 2020-05-03 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sneakersinfo', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='year',
            options={'ordering': ['-year_name']},
        ),
        migrations.AlterUniqueTogether(
            name='country',
            unique_together={('country_name',)},
        ),
        migrations.AlterUniqueTogether(
            name='order',
            unique_together={('date', 'agency', 'sneakers')},
        ),
        migrations.AlterUniqueTogether(
            name='sneakers',
            unique_together={('sneakers_name', 'publish_year')},
        ),
        migrations.AlterUniqueTogether(
            name='type',
            unique_together={('type_name',)},
        ),
        migrations.AlterUniqueTogether(
            name='year',
            unique_together={('year_name',)},
        ),
    ]
